#!/bin/sh



PID=`ps -ef |grep  wechat-group/run.py |grep -v grep |awk '{print $2}'`
echo $PID
dir=/home/kevin/pytest/wechat-group
cd $dir
start_soft()
{
    python2 $dir/run.py &>log/wechat.log &
}

stop_soft()
{

    kill -9 $PID
}

case $1 in
    start)
        start_soft;;
    stop)
        stop_soft;;
    restart)
        stop_soft ; start_soft;;
    status)
        ps -ef |grep run.py |grep -v grep;;
    *)
    echo error;;
esac
